name: layout
description: Layout encourage consistency across platforms, environments, and screen sizes by using uniform elements and spacing.
version: 1.0.1
homepage: https://github.com/jamesblasco/layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  gap: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
