name: layout
description: Layout encourage consistency across platforms, environments and screen sizes using uniform elements and spacing
version: 0.5.1
homepage: https://github.com/jamesblasco/layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  quiver: ^3.0.1
  gap: ^2.0.0-nullsafety.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
